enum ActionKind {
    Walking,
    Idle,
    Jumping
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    _0,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbddddddddbf......
        ......fcdd1111ddcf......
        .......fb111111ffff.....
        ......fffcdb1bcdddcf....
        ....fcdddcbfbfd1d1df....
        ....fd1d11ffff1f1f1f....
        ....f1f1fffffff.........
        .........fffff..........
        ..........fff...........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbddddddddbf......
        ......fcdd1111ddcf......
        .......fb111111bf.......
        ......fffddb1bdffff.....
        ....fcddddbfbfddddcf....
        ....fd1d1dfffff1d1df....
        ....f1f1ffffffff1f1f....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbddddddddbf......
        ......fcdd1111ddcf......
        .....ffff111111bf.......
        ....fcdddcdb1bdfff......
        ....fd1d1cbfbfcdddcf....
        ....f1f1fbffffd1d1df....
        .........fffffff1f1f....
        ..........fffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `],
    200,
    false
    )
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile36`, function (sprite, location) {
	
})
controller.combos.attachCombo("BAB", function () {
    animation.runImageAnimation(
    _0,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ffffffff........
        .......ffffffffff.......
        .......ffffffffff.......
        ......ffffffffffff......
        ......ffffffffffff......
        ......ffffffffffff......
        ......ffff1ff1ffff......
        ......ffff1ff1ffff......
        .......ffffffffff.......
        ......fffffffffffff.....
        ....ffffffffffffffff....
        ....ffffffffffffffff....
        ....ffffffffffffffff....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `],
    200,
    false
    )
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    _1 = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f 6 5 5 6 f f . . . . 
        . . . f 7 7 7 6 6 6 6 6 f . . . 
        . . f 7 7 7 7 8 8 8 1 1 6 f . . 
        . . f 7 7 7 7 8 8 8 1 1 5 f . . 
        . f 7 7 7 7 8 8 8 8 8 5 5 6 f . 
        . f 7 7 7 8 8 8 6 6 6 6 5 6 f . 
        . f 6 7 7 8 8 6 6 6 6 6 6 6 f . 
        . f 8 7 7 8 8 6 6 6 6 6 6 6 f . 
        . . f 8 7 7 8 6 6 6 6 6 8 f . . 
        . . f 8 8 7 8 8 6 6 6 8 6 f . . 
        . . . f 8 8 8 8 8 8 8 8 f . . . 
        . . . . f f 8 8 8 8 f f . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, _0, 50, 50)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile38`, function (sprite, location) {
	
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    _0,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f1111111df.......
        ......fd1111111ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ......fd1dfbddddbf......
        ......fbddfcdbbbcf......
        .......f11111bbcf.......
        .......f1b1fffff........
        .......fbfc111bf........
        ........ff1b1bff........
        .........fbfbfff.f......
        ..........ffffffff......
        ............fffff.......
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f1111111df.......
        ......fd1111111ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ......fd1dfbddddbf......
        ......fbddfcdbbbcf......
        .......f11111bbcf.......
        .......f1fffffff........
        .......ffc111bff........
        ........f1b1bff.........
        ........fbfbffff.f......
        .........fffffffff......
        ............fffff.......
        ........................
        ........................
        ........................
        ........................
        `],
    400,
    false
    )
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairWest, function (sprite, location) {
    tiles.setTilemap(tilemap`left`)
    _0.setPosition(128, 128)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile37`, function (sprite, location) {
	
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    tiles.setTilemap(tilemap`level5`)
    _0.setPosition(128, 128)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile1`, function (sprite, location) {
    tiles.setTilemap(tilemap`left`)
    _0.setPosition(48, 48)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    _0,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........fffff1b1f.......
        ........fb111ffbf.......
        .........fb1b1ff........
        ......f.fffbfbf.........
        ......ffffffff..........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......fd1111111f.......
        ......fdd1111111df......
        ......fddd111111df......
        ......fdddddd111df......
        ......fbddddbfd1df......
        ......fcbbbdcfddbf......
        .......fcbb11111f.......
        ........ffffffb1f.......
        .........fb111cbf.......
        .........ffb1b1f........
        ......f.ffffbfbf........
        ......fffffffff.........
        .......fffff............
        ........................
        ........................
        ........................
        ........................
        `],
    400,
    false
    )
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    _0,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111ffff.....
        ......fffcdb1bc111cf....
        ....fc111cbfbf1b1b1f....
        ....f1b1b1ffffbfbfbf....
        ....fbfbfffffff.........
        .........fffff..........
        ..........fff...........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .....ffff111111bf.......
        ....fc111cdb1bdfff......
        ....f1b1bcbfbfc111cf....
        ....fbfbfbffff1b1b1f....
        .........fffffffbfbf....
        ..........fffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `],
    200,
    false
    )
})
info.onLifeZero(function () {
    tiles.setTilemap(tilemap`level1`)
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile23`, function (sprite, location) {
	
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairSouth, function (sprite, location) {
    _0.setPosition(128, 128)
    tiles.setTilemap(tilemap`level2`)
})
let _1: Sprite = null
let _0: Sprite = null
_0 = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
_0.setPosition(128, 128)
tiles.setTilemap(tilemap`level3`)
controller.moveSprite(_0)
scene.cameraFollowSprite(_0)
info.setLife(5)
controller.combos.setExtendedComboMode(true)
forever(function () {
    music.playMelody("B G D A F C B E ", 120)
    music.playMelody("B G D A F C E C ", 120)
    music.playMelody("E B C5 G B E A C ", 120)
    music.playMelody("A F E F D G E F ", 120)
})
